### ISSUE TITLE
test 19 output says ko although it's ok

### ISSUE THREAD

**Issue by fabinca** [Yaroson/FT_SPLIT_TESTER#2]
![image](https://user-images.githubusercontent.com/73344238/121012960-9002ef80-c798-11eb-9fd8-154594671418.png)
![image](https://user-images.githubusercontent.com/73344238/121013003-9d1fde80-c798-11eb-9145-e1eda04a429a.png)

both pictures from the same test, is ok, but in the overview ko

**Comment by Ysoroko** [comment]
Thank you for your help! 
This tester was written at the very start of my s42 Cursus so it's rather poorly written 😅, thank you for going through it and your contribution!

**Comment by fabinca** [comment]
Happy to help :) and actually this tester is really helpful and quite impressive for me who's at the beginning of the 42 journey now :')
